import { useState } from "react";
import Layout from "@/components/Layout";

const docs = {
  terms: {
    title: "Terms of Service",
    updated: "April 2026",
    sections: [
      { h: "1. Acceptance of terms", p: "By accessing or using Saveur, you agree to be bound by these Terms. If you do not agree, please do not use our services." },
      { h: "2. The service", p: "Saveur is an online platform connecting diners with restaurants and delivery couriers. We do not prepare meals ourselves; food is prepared by independent partner restaurants." },
      { h: "3. Your account", p: "You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account." },
      { h: "4. Orders & payments", p: "All prices are listed in your local currency and include applicable taxes. Payment is processed at the time of order." },
      { h: "5. Cancellations & refunds", p: "Orders may be cancelled free of charge until accepted by the restaurant. Refunds are processed within 5–7 business days." },
      { h: "6. Limitation of liability", p: "Saveur is not liable for indirect or consequential damages arising from the use of our service, to the extent permitted by law." },
      { h: "7. Changes to these terms", p: "We may update these Terms periodically. Continued use of Saveur after changes constitutes acceptance of the new terms." },
    ],
  },
  privacy: {
    title: "Privacy Policy",
    updated: "April 2026",
    sections: [
      { h: "1. Information we collect", p: "We collect information you provide (name, email, address, payment details) and information generated by your use of Saveur (orders, ratings, device data)." },
      { h: "2. How we use information", p: "To provide and improve our services, process orders, prevent fraud, and communicate with you about updates and offers." },
      { h: "3. Sharing of information", p: "We share order details with restaurants and couriers as needed to fulfil your orders. We do not sell your data to advertisers." },
      { h: "4. Data security", p: "We use industry-standard encryption and security practices. All payment data is handled by PCI-DSS compliant processors." },
      { h: "5. Your rights", p: "You may access, correct, or delete your personal data at any time from your account settings, or by contacting us." },
      { h: "6. Cookies", p: "We use essential cookies to operate the site and optional cookies for analytics. You can manage preferences from the cookie banner." },
      { h: "7. Contact", p: "For privacy questions, email privacy@saveur.com." },
    ],
  },
  cookies: {
    title: "Cookies Policy",
    updated: "April 2026",
    sections: [
      { h: "1. What are cookies?", p: "Cookies are small text files stored on your device when you visit a website. They help websites remember information about your visit." },
      { h: "2. How we use cookies", p: "Essential cookies enable core features (login, cart). Analytics cookies help us improve. Marketing cookies tailor offers." },
      { h: "3. Managing cookies", p: "You can manage your preferences from the cookie banner or your browser settings. Disabling essential cookies may break parts of the site." },
    ],
  },
};

type Doc = keyof typeof docs;

export default function Legal() {
  const [active, setActive] = useState<Doc>("terms");
  const doc = docs[active];

  return (
    <Layout>
      <section className="bg-gradient-sunset border-b border-border/60">
        <div className="container-x py-12 lg:py-16 max-w-3xl space-y-3">
          <p className="text-sm font-semibold uppercase tracking-widest text-primary">Legal</p>
          <h1 className="font-display text-4xl lg:text-6xl font-semibold leading-[0.95]">{doc.title}</h1>
          <p className="text-muted-foreground">Last updated {doc.updated}</p>
        </div>
      </section>

      <section className="container-x py-10 lg:py-14 grid lg:grid-cols-12 gap-10">
        <aside className="lg:col-span-3">
          <div className="lg:sticky lg:top-24 space-y-1">
            {(Object.keys(docs) as Doc[]).map(k => (
              <button key={k} onClick={() => setActive(k)}
                className={`w-full text-left px-4 py-3 rounded-xl text-sm font-semibold transition-colors ${
                  active === k ? "bg-foreground text-background" : "text-muted-foreground hover:text-foreground hover:bg-secondary"
                }`}>
                {docs[k].title}
              </button>
            ))}
          </div>
        </aside>
        <article className="lg:col-span-9 space-y-8">
          {doc.sections.map(s => (
            <div key={s.h} className="space-y-3">
              <h2 className="font-display text-2xl font-semibold">{s.h}</h2>
              <p className="text-muted-foreground leading-relaxed">{s.p}</p>
            </div>
          ))}
        </article>
      </section>
    </Layout>
  );
}
